const colors = {
  black: '#000000',
  white: '#FFFFFF',
  appButtonColor: '#FD7B08',
  backgroundColor: '#B8B8B8',
  greenIconColor: '#4CD964',
  greyIconColor: '#4E5761',
  greyTextColor: '#ADB5BD',
  greyBackgroundColor: '#F6F6F6',
  shadowColor: '#0000001F',
  shadowColor1: 'greyIconColor',
  borderColor: '#E2E2E2',
  greenFontColor: '#5ADA8D',
  appTabActiveIconColor: '#FD7B08',
  appTabInactivecolor: '#A4A4A4',
  redTextColor: '#FD7B08',
  greenTextColor: '#23F58C',
  pendingColor: '#FD7B08',
  yellowIcon: '#f9d380',
  seperatorColor: '#E9ECE7',
  textColorBlackShade: '#0D1904',
  starColor: '#FFCC00',
  textContent: '#7B7B7B',
  vegColor: '#3FD466',
  cardBackground: '#F5F5F5',
  listBackground: '#FDFFFC',
  blueText: '#2D9DFF',
  borderColor1: '#DDDDDD',
  redTitle: '#FD7B08',
  greyTimeText: '#BDC1BB',
  gradientPink: '#FFE8E8',
  greyClaBack: '#E3E3E3',
  calenderSelection: '#FD7B08',
  imageBack: '#D2D2D2',
  pinkButtonback: '#FFDCDC',
  darkgreyback: '#343434',
  greylighttext: '#CCCCCC',
  greyBackgroundColor1: '#E8E8E8',
  greyBackgroundColor2: '#B2B2B2',
};

export default colors;
