import {Dimensions, StyleSheet} from 'react-native';
import Colors from '../../../Theams/Colors';
export default StyleSheet.create({
  containerMain: {
    backgroundColor: Colors.appPrimaryColor,
    flex: 1,
    height: Dimensions.get('window').height,
  },
  createIDContainer: {
    flex: 1,
    flexDirection: 'column',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    backgroundColor: Colors.appBlackColor,
    alignItems: 'center',
  },
  planCards: {
    flex: 0.4,
    marginTop: 20,
    padding: 5,
    backgroundColor: 'black',
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: 10,
    display: 'none',
  },
  planDeatils: {
    padding: 5,
    backgroundColor: '#171616',
    width: '90%',
    borderRadius: 10,
    marginTop: 10,
  },
  topIcon: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageIcon: {
    height: 150,
    width: 150,
    borderColor: Colors.appBlackColor,
    borderWidth: 0.5,
    borderRadius: 35,
  },
  bronzeCard: {
    flex: 0.33,
    backgroundColor: '#171616',
    padding: 10,
    borderRadius: 10,
    height: '100%',
    margin: 8,
    alignItems: 'center',
    width: 20,
  },
  goldCard: {
    flex: 0.33,
    backgroundColor: '#171616',
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
    height: '100%',
    margin: 8,
    width: 20,
  },
  silverCard: {
    flex: 0.33,
    padding: 10,
    alignItems: 'center',
    borderRadius: 10,
    height: '100%',
    backgroundColor: '#171616',
    margin: 8,
    width: 20,
  },
  modalText: {
    borderRadius: 10,
    backgroundColor: '#171616',
    fontSize: 14,
    color: '#d5d1d1',
    marginBottom: 15,
  },
  planDetailsText: {
    color: '#d5d1d1',
    marginLeft: 'auto',
    padding: 5,
  },

  hexagon: {
    width: 50,
    height: 25,
    marginTop: 20,
  },
  hexagonInner: {
    width: 45,
    height: 25,
    backgroundColor: 'red',
  },
  hexagonAfter: {
    position: 'absolute',
    bottom: -12,
    left: 0,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: 22,
    borderLeftColor: 'transparent',
    borderRightWidth: 22,
    borderRightColor: 'transparent',
    borderTopWidth: 12,
    borderTopColor: 'red',
  },
  hexagonBefore: {
    position: 'absolute',
    top: -12,
    left: 0,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: 22,
    borderLeftColor: 'transparent',
    borderRightWidth: 22,
    borderRightColor: 'transparent',
    borderBottomWidth: 12,
    borderBottomColor: 'red',
  },
});
