import {Dimensions, StyleSheet} from 'react-native';
import Colors from '../../../Theams/Colors';

export default StyleSheet.create({
  containerMain: {
    backgroundColor: Colors.appPrimaryColor,
  },
  containerNotification: {
    backgroundColor: Colors.backgroundColor,
    flex: 1,
    paddingTop: 14,
  },
  centreCard: {
    backgroundColor: Colors.appBlackColor,
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 1,
    shadowOffset: {width: 2, height: 2},
    elevation: 10,
  },
  centeredView: {
    width: '100%',
    flex: 1,
    top: 200,
  },
  modalView: {
    margin: 30,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
  },
  image: {
    height: 100,
    width: 100,
  },
  createAnnouncement: {
    flex: 0.2,
    flexDirection: 'column',
    alignItems: 'center',
    width: '80%',
    marginTop: 40,
    justifyContent: 'center',
    backgroundColor: 'black',
  },
  tipsText: {
    color: Colors.appPrimaryColor,
  },
  tipsSubText: {
    color: 'white',
    marginVertical: 20,
  },

  createText: {
    marginTop: 20,
    flex: 0.05,
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
    paddingVertical: 15,
    justifyContent: 'center',
    backgroundColor: Colors.appBlackColorLight,
  },
  promotionCard: {
    flex: 1,
    flexDirection: 'column',
    marginTop: 20,
    width: '100%',
    paddingBottom: 40,
    borderRadius: 5,
  },
  text: {
    marginTop: 20,
    fontSize: 12,
    color: 'white',
  },
  createTextOnly: {
    color: Colors.appWhiteColor,
    marginHorizontal: 10,
    fontSize: 12,
  },
  myids: {
    color: 'white',
    marginLeft: 10,
    fontSize: 15,
    marginRight: 'auto',
  },
  centralCardView: {
    flex: 1,
    backgroundColor: 'black',
    width: '50%',
    height: '70%',
    flexDirection: 'row',
    marginHorizontal: 45,
    borderRadius: 20,
  },
  depositCard: {
    backgroundColor: Colors.appBlackColor + 'cf',
    paddingHorizontal: 5,
    paddingVertical: 10,
    height: 140,
    minWidth: 80,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  centerCard: {
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.appBlackColorLight,
    borderRadius: 10,
    height: 190,
    padding: 24,
  },
  blankCard: {
    flex: 0.4,
    backgroundColor: 'white',
  },
  withdrawCard: {
    flexDirection: 'row',
    flex: 1,
    borderRadius: 20,
    alignItems: 'center',
    backgroundColor: Colors.buttonBackgroundColor,
    minWidth: 130,
    padding: 5,
  },
  upperContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    marginHorizontal: 30,
  },
  lowerContainer: {
    backgroundColor: Colors.appBlackColor,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  lowerBox1: {
    flexDirection: 'column',
    marginTop: 20,
    width: '100%',
    overflow: 'hidden',
  },
  carouselCards: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: 'green',
  },
  buttonClose: {
    marginLeft: 'auto',
  },
  modalText: {
    borderRadius: 5,
    backgroundColor: 'white',
    fontSize: 20,
    height: 50,
    marginBottom: 5,
  },
  notetext: {
    borderRadius: 5,
    backgroundColor: 'white',
    fontSize: 14,
    marginBottom: 10,
  },
  dropdownStyle: {
    borderRadius: 10,
    marginVertical: 20,
    width: Dimensions.get('window').width - 120,
  },
  listContainer: {
    backgroundColor: Colors.appBlackColor,
    flex: 1,
    marginHorizontal: 20,
    marginVertical: 5,
    borderRadius: 10,
    flexDirection: 'row',
    minHeight: 30,
    alignItems: 'center',
    padding: 10,
    borderTopRightRadius: 5,
  },
  marginVertical: {
    marginVertical: 5,
  },
});
