export const banksList = [
  'Abhyudaya Co-op Bank Ltd',
  'Abu Dhabi Commercial Bank Ltd',
  'National Bank of Abu Dhabi PJSC',
  'AB Bank Ltd',
  'Ahmedabad Mercantile Co-op Bank',
  'Allahabad Bank',
  'Andhra Bank',
  'Antwerp Diamond Bank Mumbai',
  'Australia and New Zealand Banking Group Limited',
  'Axis Bank',
  'Bank Of America',
  'Bank Of Bahrain And Kuwait',
  'Bank of Baroda',
  'Bank Of Ceylon',
  'Bank of India',
  'Bank Of Maharashtra',
  'Bank Of Nova Scotia',
  'Bank Of Tokyo-Mitsubishi Ufj Ltd',
  'Bank Internasional Indonesia',
  'Barclays Bank Plc',
  'Bassein Catholic Co-op Bank Ltd',
  'Bharat Co-op Bank (Mumbai) Ltd',
  'BNP Paribas',
  'Canara Bank',
  'Catholic Syrian Bank Ltd',
  'Central Bank of India',
  'Chinatrust Commercial Bank',
  'Citibank India',
  'Citizencredit Co-op Bank Ltd',
  'City Union Bank Ltd',
  'Corporation Bank',
  'Cosmos Co-op Bank Ltd',
  'Credit Agricole Corp and Investment Bank',
  'Commonwealth Bank of Australia',
  'DBS Bank',
  'Dena Bank',
  'Deutsche Bank Ag',
  'Development Credit Bank',
  'Dhanlaxmi Bank Ltd',
  'Dicgc',
  'Doha Bank',
  'Dombivli Nagari Sahakari Bank Ltd',
  'Export-Import Bank of India',
  'Federal Bank Ltd',
  'Firstrand Bank Ltd',
  'Greater Bombay Co-op Bank Ltd',
  'HDFC Bank',
  'HSBC',
  'HSBC Bank Oman S.A.O.G.',
  'ICICI Bank',
  'IDBI Bank',
  'IDFC Bank Limited',
  'Indian Bank',
  'Indian Overseas Bank',
  'IndusInd Bank Ltd.',
  'Industrial and Commercial Bank of China Ltd.',
  'ING Vysya Bank',
  'Industrial Bank of  Korea',
  'Jammu & Kashmir Bank Ltd.',
  'Janakalyan Sahakari Bank Ltd',
  'Janata Sahkari Bank Ltd Pune',
  'Jpmorgan Chase Bank',
  'Kalupur Commercial Co-op Bank Ltd',
  'Kalyan Janata Sahakari Bank Ltd',
  'Kapole Co-op Bank',
  'Karnataka Bank Ltd.',
  'Karnataka State Co-op Apex Bank',
  'Karur Vysya Bank',
  'Kotak Mahindra Bank',
  'KEB  Hana Bank',
  'Krung Thai Bank PCL Mumbai',
  'Lakshmi Vilas Bank Ltd',
  'Mahanagar Co-op Bank Ltd',
  'Maharashtra State Co-operative Bank Limited',
  'Mashreq Bank Psc',
  'Mehsana Urban Co-op Bank Ltd',
  'Mizuho Corporate Bank Ltd',
  'Nainital Bank Ltd',
  'National Australia Bank',
  'New India Co-op Bank Ltd',
  'Nkgsb Co-op Bank Ltd',
  'Nutan Nagarik Sahakari Bank Ltd',
  'Oman International Bank Saog',
  'Oriental Bank of Commerce',
  'Parsik Janata Sahakari Bank Ltd',
  'Punjab and Maharashtra Bank Ltd.',
  'Punjab National Bank',
  'Punjab & Sind Bank',
  'Qatar National Bank(QPSC)',
  'Rajkot Nagarik Sahakari Bank Ltd',
  'Ratnakar Bank Ltd',
  'Reserve Bank Of India',
  'Royal bank of scotland',
  'Rabobank International',
  'Sberbank',
  'Saraswat Co-operative Bank Ltd.',
  'Shamrao Vithal Co-op Bank Ltd',
  'Shinhan Bank',
  'Societe Generale',
  'Sonali Bank Ltd.',
  'South Indian Bank',
  'Standard Chartered Bank',
  'State Bank Of Bikaner And Jaipur',
  'State Bank of Hyderabad',
  'State Bank of India',
  'SBI Global Factors Ltd(SBIGFL) factoring Unit',
  'India Factoring and Finance Solutions Pvt. Ltd',
  'IFCI Factors Limited',
  'Bombay Mercantile Co-operative bank Limited',
  'State Bank Of Mauritius Ltd',
  'State Bank of Mysore',
  'State Bank Of Patiala',
  'State Bank Of Travancore',
  'State Bank of Saurashtra',
  'Sumitomo Mitsui Banking Corporation',
  'Surat Peoples Co-op Bank Ltd',
  'Syndicate Bank',
  'Tamilnad Mercantile Bank Ltd',
  'Thane Janta Sahakari Bank, Ltd.',
  'The Karad Urban Co-op Bank Ltd',
  'The Nasik Merchants Co-op Bank Ltd',
  'UBS AG',
  'UCO Bank',
  'Union Bank of India',
  'United Bank of India',
  'United Overseas Bank',
  'Vijaya Bank',
  'West Bengal State Co-op Bank Ltd',
  'Westpac Banking Corporation',
  'Woori Bank',
  'Yes Bank',
  'Emirates NBD Bank  PJSC',
];
